Repository openshift-psap/special-resource-operator, pull requests merged in 2021-12, with the labels that each got.

#162 Fix test lint. Remove gh actions in favor of prow
  .github/workflows/go-lint.yaml
  .github/workflows/helm-lint.yaml
  .github/workflows/kube-lint.yaml
  .github/workflows/unit.yaml
  .github/workflows/verify.yaml
  test/deploy/deploy.go
  test/e2e/basic/ping-pong_test.go
  test/e2e/basic/simple-kmod_test.go
  test/e2e/basic/specialresource_test.go
  test/framework/create_from_yaml.go
  test/undeploy/undeploy.go
Labels: approved, lgtm, ok-to-test

#166 Refactoring some makefile target to improve the CI.
  .github/workflows/e2e.yaml
  .github/workflows/k8s-e2e.yaml
  Makefile
  Makefile.helper.mk
  api/v1beta1/zz_generated.deepcopy.go
Labels: approved, lgtm

#175 Convert existing unit tests to Ginkgo
  cmd/cli/cli_test.go
  cmd/leaderelection/options_test.go
  pkg/assets/assets_test.go
  pkg/conditions/conditions_test.go
  pkg/kernel/kernel_test.go
Labels: approved, lgtm, ok-to-test

#154 Add more unit tests - Ginkgo version
  pkg/cache/cache.go
  pkg/cache/cache_test.go
  pkg/filter/filter.go
  pkg/filter/filter_test.go
  pkg/hash/hash_test.go
  pkg/osversion/osversion.go
  pkg/osversion/osversion_test.go
  vendor/k8s.io/apimachinery/pkg/util/rand/rand.go
  vendor/k8s.io/client-go/testing/actions.go
  vendor/k8s.io/client-go/testing/fake.go
  vendor/k8s.io/client-go/testing/fixture.go
  vendor/k8s.io/client-go/testing/interface.go
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/client.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/doc.go
Labels: approved, lgtm, ok-to-test

#126 Remove the pkg/exit package
  controllers/resources.go
  controllers/runtime.go
  controllers/scale_up_down.go
  controllers/specialresource.go
  controllers/status.go
  controllers/upgrade.go
  pkg/exit/exit.go
  test/deploy/deploy.go
  test/e2e/basic/ping-pong_test.go
  test/e2e/basic/simple-kmod_test.go
  test/e2e/basic/specialresource_test.go
  test/framework/create_from_yaml.go
  test/undeploy/undeploy.go
Labels: approved, lgtm, ok-to-test

#176 Fixing the getRuntimeInfo function
  Dockerfile.special-resource-operator-build
  controllers/runtime.go
Labels: approved, lgtm, ok-to-test

#174 MGMT-8409: Change pkg/cluster into a typed interface
  controllers/runtime.go
  main.go
  pkg/cluster/cluster.go
  pkg/cluster/mock_cluster_api.go
  pkg/upgrade/upgrade.go
Labels: approved, lgtm, ok-to-test

#167 MGMT-8398: Change pkg/registry to a typed interface
  main.go
  pkg/registry/mock_registry_api.go
  pkg/registry/registry.go
  pkg/upgrade/upgrade.go
Labels: approved, lgtm, ok-to-test

#179 Upgrade golangci-lint version to 1.43
  Makefile.helper.mk
Labels: approved, lgtm, ok-to-test

#181 Adding pmtk as an approver.
  OWNERS
Labels: approved, lgtm, ok-to-test

#173 MGMT-8394: change SRO CR finzalizer to support errors
  controllers/finalizers.go
Labels: approved, lgtm, ok-to-test

#163 Add even more Ginkgo unit tests
  pkg/lifecycle/lifecycle_test.go
  pkg/proxy/proxy.go
  pkg/proxy/proxy_test.go
  pkg/resource/resource.go
  pkg/resource/resource_test.go
  pkg/scheme/scheme_test.go
  pkg/slice/slice_test.go
  pkg/state/state_test.go
  pkg/storage/storage.go
  pkg/storage/storage_test.go
Labels: approved, lgtm, ok-to-test

#178 Removing Dockerfile duplication.
  Dockerfile
  Dockerfile.ubi8
  Makefile
Labels: approved, lgtm, ok-to-test

#172 Fixing 'patch' command on 'patch' makefile target.
  Makefile.helper.mk
  scripts/patch.sh
Labels: approved, lgtm, ok-to-test

#183 Build manager using makefile within dockerfile
  Dockerfile
  Makefile
Labels: approved, lgtm, ok-to-test

#185 Fix the Dockerfile to include the file getter
  Dockerfile
Labels: approved, lgtm, ok-to-test

#180 MGMT-8421: add nodes metrics for DaemonSet and Deployment
  pkg/lifecycle/lifecycle.go
  pkg/lifecycle/lifecycle_test.go
  pkg/metrics/metrics.go
  pkg/metrics/metrics_test.go
  pkg/resource/resource.go
Labels: approved, lgtm, ok-to-test

#188 MGMT-8390: exclude helm charts built artifacts from git management
  .gitignore
  Dockerfile
  Makefile.helm.mk
  Makefile.specialresource.mk
Labels: approved, lgtm, ok-to-test

#165 MGMT-8348: Change pkg/upgrade/ into a typed interface
  controllers/runtime.go
  controllers/specialresource_controller.go
  controllers/upgrade.go
  main.go
  pkg/cluster/cluster.go
  pkg/upgrade/mock_upgrade_api.go
  pkg/upgrade/upgrade.go
  pkg/upgrade/upgrade_test.go
Labels: approved, lgtm, ok-to-test

#191 Removing helm-lint from GH actions.
  .github/workflows/helm-lint.yaml
Labels: approved, lgtm, ok-to-test

#193 Removing bin/ from git control.
  .gitignore
Labels: approved, lgtm, ok-to-test

#192 Make pkg/resource expose an interface
  controllers/resources.go
  controllers/specialresource.go
  controllers/specialresource_controller.go
  main.go
  pkg/helmer/helmer.go
  pkg/metrics/mock_metrics_api.go
  pkg/resource/resource.go
  pkg/resource/resource_test.go
Labels: approved, lgtm, ok-to-test

#194 Removing 'kube-lint' Github actions.
  .github/workflows/kube-lint.yaml
Labels: approved, lgtm, ok-to-test

#197 Bug 2033579: allow the ConfigMap's data field to be empty
  pkg/storage/storage.go
  pkg/storage/storage_test.go
Labels: approved, bugzilla/valid-bug, bugzilla/severity-high, lgtm, ok-to-test

#190 Moving all image-building dependencies to be executed in Dockerfile.
  Dockerfile
  Makefile
  Makefile.helm.mk
Labels: approved, lgtm, ok-to-test

#199 Make pkg/lifecycle a typed interface
  controllers/finalizers.go
  controllers/specialresource_controller.go
  main.go
  pkg/filter/filter.go
  pkg/lifecycle/lifecycle.go
  pkg/lifecycle/lifecycle_test.go
  pkg/lifecycle/mock_lifecycle_api.go
  pkg/poll/poll.go
  pkg/resource/resource.go
  pkg/resource/resource_test.go
Labels: approved, lgtm, ok-to-test

#200 MGMT-8483 Refactor pkg/filter into an interface
  controllers/specialresource.go
  controllers/specialresource_controller.go
  main.go
  pkg/filter/filter.go
  pkg/filter/filter_test.go
  pkg/resource/resource.go
  pkg/resource/resource_test.go
Labels: approved, lgtm, ok-to-test

#202 Initialize PollActions for SpecialResourceReconciler
  main.go
Labels: approved, lgtm, ok-to-test

#203 Refactor pkg/storage
  controllers/specialresource.go
  controllers/specialresource_controller.go
  main.go
  pkg/filter/filter.go
  pkg/lifecycle/lifecycle.go
  pkg/lifecycle/lifecycle_test.go
  pkg/poll/poll.go
  pkg/storage/mock_storage_api.go
  pkg/storage/storage.go
  pkg/storage/storage_test.go
Labels: approved, lgtm, ok-to-test

#201 Fixing SRO deployment on custom namespace.
  Makefile.helper.mk
  controllers/status.go
  go.mod
  go.sum
  test/e2e/basic/ping-pong_test.go
  test/e2e/basic/simple-kmod_test.go
  test/e2e/basic/specialresource_test.go
  test/e2e/basic/util_test.go
  test/framework/clientset.go
  vendor/github.com/kelseyhightower/envconfig/.travis.yml
  vendor/github.com/kelseyhightower/envconfig/LICENSE
  vendor/github.com/kelseyhightower/envconfig/MAINTAINERS
  vendor/github.com/kelseyhightower/envconfig/README.md
  vendor/github.com/kelseyhightower/envconfig/doc.go
  vendor/github.com/kelseyhightower/envconfig/env_os.go
  vendor/github.com/kelseyhightower/envconfig/env_syscall.go
  vendor/github.com/kelseyhightower/envconfig/envconfig.go
  vendor/github.com/kelseyhightower/envconfig/usage.go
  vendor/modules.txt
Labels: approved, lgtm, ok-to-test

#189 Make pkg/helmer expose an interface
  .patches/options.patch.go
  Makefile.helper.mk
  controllers/resources.go
  controllers/specialresource.go
  controllers/specialresource_controller.go
  main.go
  pkg/helmer/helmer.go
  pkg/helmer/helmer_test.go
  pkg/helmer/testdata/index.yaml
  pkg/helmer/testdata/test-chart-0.1.0.tgz
  pkg/helmer/testdata/test-chart/.helmignore
  pkg/helmer/testdata/test-chart/Chart.yaml
  pkg/helmer/testdata/test-chart/index.yaml
  pkg/helmer/testdata/test-chart/templates/NOTES.txt
  pkg/helmer/testdata/test-chart/templates/_helpers.tpl
  pkg/helmer/testdata/test-chart/templates/deployment.yaml
  pkg/helmer/testdata/test-chart/templates/hpa.yaml
  pkg/helmer/testdata/test-chart/templates/ingress.yaml
  pkg/helmer/testdata/test-chart/templates/service.yaml
  pkg/helmer/testdata/test-chart/templates/serviceaccount.yaml
  pkg/helmer/testdata/test-chart/templates/tests/test-connection.yaml
  pkg/helmer/testdata/test-chart/values.yaml
  pkg/registry/registry.go
  pkg/resource/mock_resource_api.go
  pkg/resource/resource.go
Labels: approved, lgtm, ok-to-test

#207 MGMT-8720: support ARM DTK kernel versions
  pkg/upgrade/upgrade.go
Labels: approved, lgtm, ok-to-test

#208 Removing e2e GH action.
  .github/workflows/e2e.yaml
Labels: approved, lgtm, ok-to-test

#209 MGMT-8725: add debug info for Build error case
  pkg/upgrade/upgrade.go
Labels: approved, lgtm, ok-to-test

#210 Using ENV variable instead of hardcodded 'kubectl' in Makefiles.
  Makefile
  Makefile.helper.mk
  Makefile.specialresource.mk
Labels: approved, lgtm, ok-to-test

#211 MGMT-8728: make assets a typed interface package with mock
  controllers/resources.go
  controllers/specialresource_controller.go
  main.go
  pkg/assets/assets.go
  pkg/assets/assets_test.go
  pkg/assets/mock_assets_api.go
  test/deploy/deploy.go
  test/undeploy/undeploy.go
Labels: approved, lgtm, ok-to-test

#213 MGMT-8731: convert kernel package to be a typed interface package wit…
  controllers/runtime.go
  controllers/specialresource_controller.go
  main.go
  pkg/assets/assets.go
  pkg/filter/filter.go
  pkg/filter/filter_test.go
  pkg/kernel/kernel.go
  pkg/kernel/kernel_test.go
  pkg/kernel/mock_kernel_api.go
  pkg/resource/resource.go
  pkg/resource/resource_test.go
Labels: approved, lgtm, ok-to-test
