Repository openshift-psap/special-resource-operator, pull requests merged in 2021-03, with the labels that each got.

#30 lustre-client and runtime.go updates
  config/recipes/lustre-client/0000-lustre-client-cr.yaml
  config/recipes/lustre-client/manifests/1100-lustre-csi-secret.yaml
  controllers/runtime.go
Labels: approved, lgtm, ok-to-test

#34 Update lustre-client
  config/recipes/lustre-client/0000-lustre-client-cr.yaml
  config/recipes/lustre-client/manifests/0000-buildconfig.yaml
  config/recipes/lustre-client/manifests/1000-driver-container.yaml
Labels: approved, lgtm, ok-to-test

#33 Added Rolling Upgrade Support
  config/manager/kustomization.yaml
  config/recipes/driver-container-base/manifests/0000-driver-container-base-build.yaml
  config/recipes/simple-kmod/manifests/1000-driver-container.yaml
  controllers/resources.go
  controllers/runtime.go
  controllers/scale_up_down.go
  controllers/specialresource.go
  controllers/specialresource_controller.go
  controllers/status.go
  controllers/upgrade.go
  controllers/waitfor.go
  manifests/0012_deployment_special-resource-controller-manager.yaml
  pkg/hash/hash.go
  pkg/warn/warn.go
Labels: approved, lgtm

#37 Bug fixes: finalizers, e2e tests, runtime.go, status.go
  controllers/runtime.go
  controllers/specialresource.go
  controllers/specialresource_controller.go
  controllers/status.go
  pkg/osversion/osversion.go
  test/e2e/basic/simple-kmod.go
  test/e2e/basic/util.go
Labels: approved, lgtm, ok-to-test, tide/merge-method-squash

#36 Add support for cert-manager and an example SpecialResource
  config/rbac/role.yaml
  config/recipes/ping-pong/0000-ping-pong-cr.yaml
  config/recipes/ping-pong/README.md
  config/recipes/ping-pong/manifests/0001_secret.yaml
  config/recipes/ping-pong/manifests/0002_issuer.yaml
  config/recipes/ping-pong/manifests/0003_certificates.yaml
  config/recipes/ping-pong/manifests/0004_server.yaml
  config/recipes/ping-pong/manifests/0005_client.yaml
  config/recipes/ping-pong/manifests/kustomization.yaml
  controllers/resources.go
  controllers/specialresource.go
  manifests/0004_clusterrole_special-resource-manager-role.yaml
Labels: approved, lgtm, ok-to-test
