Repository openshift-psap/special-resource-operator, pull requests merged in 2021-08, with the labels that each got.

#74 Declare supported architectures in CSV
  bundle/4.9/manifests/special-resource-operator.v4.9.0.clusterserviceversion.yaml
  charts/deprecated/driver-container-base-0.1.0.tgz
  charts/deprecated/index.yaml
  charts/example/centos-simple-kmod-0.0.1.tgz
  charts/example/connaisseur-0.2.0.tgz
  charts/example/index.yaml
  charts/example/multi-build-0.0.1.tgz
  charts/example/ping-pong-0.0.1.tgz
  charts/example/simple-kmod-0.0.1.tgz
  charts/experimental/cert-manager-1.4.0.tgz
  charts/experimental/index.yaml
  charts/experimental/simple-kmod-0.0.1.tgz
  charts/inaccel/index.yaml
  charts/lustre/index.yaml
  charts/lustre/lustre-aws-fsx-0.0.1.tgz
  charts/olm/cert-manager-0.0.1.tgz
  charts/olm/index.yaml
  charts/staging/index.yaml
  charts/staging/shipwright-4.7.0.tgz
  charts/xilinx/fpga-xrt-driver-4.7.11.tgz
  charts/xilinx/index.yaml
  config/manifests/bases/special-resource-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  manifests/0004_clusterrole_special-resource-manager-role.yaml
  manifests/0013_deployment_special-resource-controller-manager.yaml
Labels: approved, lgtm, ok-to-test

#75 Allow the pullSecret artifact to be empty
  api/v1beta1/specialresource_types.go
  bundle/4.9/manifests/sro.openshift.io_specialresources.yaml
  config/crd/bases/sro.openshift.io_specialresources.yaml
Labels: approved, lgtm, ok-to-test

#72 Move the helmer structure to the api folder
  api/v1beta1/specialresource_types.go
  controllers/specialresource.go
  pkg/helmer/api/v1beta1/helmer_types.go
  pkg/helmer/helmer.go
Labels: approved, lgtm

#76 Infoscale bug fixes
  .github/workflows/e2e.yaml
  .patches/getter.patch.go
  Makefile.helm.mk
  charts/deprecated/driver-container-base-0.1.0.tgz
  charts/deprecated/index.yaml
  charts/example/centos-simple-kmod-0.0.1.tgz
  charts/example/connaisseur-0.2.0.tgz
  charts/example/index.yaml
  charts/example/multi-build-0.0.1.tgz
  charts/example/ping-pong-0.0.1.tgz
  charts/example/simple-kmod-0.0.1.tgz
  charts/experimental/cert-manager-1.4.0.tgz
  charts/experimental/index.yaml
  charts/experimental/simple-kmod-0.0.1.tgz
  charts/inaccel/fpga-operator-1.2.1.tgz
  charts/inaccel/fpga-operator-2.0.1.tgz
  charts/inaccel/fpga-operator-2.0.1/Chart.yaml
  charts/inaccel/fpga-operator-2.0.1/README.md
  charts/inaccel/fpga-operator-2.0.1/fpga-operator.yaml
  charts/inaccel/fpga-operator-2.0.1/templates/NOTES.txt
  charts/inaccel/fpga-operator-2.0.1/templates/_helpers.tpl
  charts/inaccel/fpga-operator-2.0.1/templates/cluster-role-binding.yaml
  charts/inaccel/fpga-operator-2.0.1/templates/cluster-role.yaml
  charts/inaccel/fpga-operator-2.0.1/templates/csi-driver.yaml
  charts/inaccel/fpga-operator-2.0.1/templates/daemon-set.yaml
  charts/inaccel/fpga-operator-2.0.1/templates/secret.yaml
  charts/inaccel/fpga-operator-2.0.1/values.yaml
  charts/inaccel/index.yaml
  charts/infoscale/index.yaml
  charts/infoscale/infoscale-vtas-0.0.1.tgz
  charts/lustre/index.yaml
  charts/lustre/lustre-aws-fsx-0.0.1.tgz
  charts/olm/cert-manager-0.0.1.tgz
  charts/olm/index.yaml
  charts/staging/index.yaml
  charts/staging/shipwright-4.7.0.tgz
  charts/xilinx/fpga-xrt-driver-4.7.11.tgz
  charts/xilinx/fpga-xrt-driver-4.7.11/fpga-xrt-driver.yaml
  charts/xilinx/fpga-xrt-driver-4.7.11/templates/1000-driver-container.yaml
  charts/xilinx/index.yaml
  config/manager/kustomization.yaml
  controllers/finalizers.go
  controllers/resources.go
  controllers/specialresource.go
  controllers/status.go
  docs/debug.md
  manifests/0001_customresourcedefinition_specialresources.sro.openshift.io.yaml
  manifests/0013_deployment_special-resource-controller-manager.yaml
  pkg/cache/cache.go
  pkg/helmer/helmer.go
  pkg/poll/poll.go
  vendor/helm.sh/helm/v3/pkg/getter/getter.patch.go
Labels: approved, lgtm

#77 Infoscale chart fixes for deployment
  charts/infoscale/infoscale-vtas-0.0.1/templates/2000-infoscale-rest-certificate.yaml
  charts/infoscale/infoscale-vtas-0.0.1/templates/3000-driver-container.yaml
  charts/infoscale/infoscale-vtas-0.0.1/templates/4000-infoscale-fencing-certificate.yaml
  charts/infoscale/infoscale-vtas-0.0.1/templates/4100-infoscale-fencing-driver.yaml
  charts/infoscale/infoscale-vtas-0.0.1/templates/6000-infoscale-csi-driver.yaml
Labels: approved, lgtm, ok-to-test

#81 Misc fixes to InfoScale chart
  charts/infoscale/infoscale-vtas-0.0.1/templates/3000-driver-container.yaml
Labels: approved, needs-ok-to-test, lgtm

#78 Allow chart dependency version pinning, update readme, bundle fixes
  Makefile.helper.mk
  README.md
  bundle/4.9/manifests/special-resource-operator.v4.9.0.clusterserviceversion.yaml
  bundle/image-references
  charts/deprecated/driver-container-base-0.1.0.tgz
  charts/deprecated/index.yaml
  charts/example/centos-simple-kmod-0.0.1.tgz
  charts/example/connaisseur-0.2.0.tgz
  charts/example/index.yaml
  charts/example/multi-build-0.0.1.tgz
  charts/example/ping-pong-0.0.1.tgz
  charts/example/ping-pong-0.0.1/ping-pong.yaml
  charts/example/simple-kmod-0.0.1.tgz
  charts/experimental/cert-manager-1.4.0.tgz
  charts/experimental/index.yaml
  charts/experimental/simple-kmod-0.0.1.tgz
  charts/inaccel/fpga-operator-2.0.1.tgz
  charts/inaccel/index.yaml
  charts/infoscale/index.yaml
  charts/infoscale/infoscale-vtas-0.0.1.tgz
  charts/lustre/index.yaml
  charts/lustre/lustre-aws-fsx-0.0.1.tgz
  charts/olm/cert-manager-0.0.1.tgz
  charts/olm/index.yaml
  charts/staging/index.yaml
  charts/staging/shipwright-4.7.0.tgz
  charts/xilinx/fpga-xrt-driver-4.7.11.tgz
  charts/xilinx/index.yaml
  config/manager/kustomization.yaml
  config/manifests/bases/special-resource-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  manifests/0004_clusterrole_special-resource-manager-role.yaml
  manifests/0013_deployment_special-resource-controller-manager.yaml
  pkg/helmer/helmer.go
  pkg/rbac/rbac.go
Labels: approved, lgtm, ok-to-test

#80 Minor fixes
  .gitignore
  docs/debug.md
  docs/recipes.md
  scripts/rename.sh
Labels: approved, lgtm, ok-to-test

#82 Added OnDelete lifecycle management for DaemonSets
  bundle/4.9/manifests/special-resource-lifecycle_v1_configmap.yaml
  bundle/4.9/manifests/special-resource-operator.v4.9.0.clusterserviceversion.yaml
  charts/deprecated/driver-container-base-0.1.0.tgz
  charts/deprecated/index.yaml
  charts/example/centos-simple-kmod-0.0.1.tgz
  charts/example/centos-simple-kmod-0.0.1/templates/3000-driver-container.yaml
  charts/example/connaisseur-0.2.0.tgz
  charts/example/index.yaml
  charts/example/multi-build-0.0.1.tgz
  charts/example/ping-pong-0.0.1.tgz
  charts/example/simple-kmod-0.0.1.tgz
  charts/example/simple-kmod-0.0.1/templates/1000-driver-container.yaml
  charts/experimental/cert-manager-1.4.0.tgz
  charts/experimental/index.yaml
  charts/experimental/simple-kmod-0.0.1.tgz
  charts/global-values.yaml
  charts/inaccel/fpga-operator-2.0.1.tgz
  charts/inaccel/index.yaml
  charts/infoscale/index.yaml
  charts/infoscale/infoscale-vtas-0.0.1.tgz
  charts/lustre/index.yaml
  charts/lustre/lustre-aws-fsx-0.0.1.tgz
  charts/olm/cert-manager-0.0.1.tgz
  charts/olm/index.yaml
  charts/staging/index.yaml
  charts/staging/shipwright-4.7.0.tgz
  charts/xilinx/fpga-xrt-driver-4.7.11.tgz
  charts/xilinx/index.yaml
  config/manager/kustomization.yaml
  config/manager/lifecycle.yaml
  controllers/resources.go
  controllers/specialresource.go
  manifests/0012_configmap_special-resource-lifecycle.yaml
  manifests/0013_service_special-resource-controller-manager-metrics-service.yaml
  manifests/0014_deployment_special-resource-controller-manager.yaml
  manifests/0015_clusteroperator_special-resource-operator.yaml
  manifests/0016_servicemonitor_special-resource-controller-manager-metrics-monitor.yaml
  pkg/dependencies/dependencies.go
  pkg/filter/filter.go
  pkg/lifecycle/lifecycle.go
  pkg/poll/poll.go
  pkg/storage/storage.go
Labels: approved, lgtm

#84 Add OLM skipRange to CSV
  bundle/4.9/manifests/special-resource-operator.v4.9.0.clusterserviceversion.yaml
  config/manager/kustomization.yaml
  config/manifests/bases/special-resource-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#86 Add pacevedo as reviewer to OWNERS
  OWNERS
Labels: approved, lgtm

#87 Fix multiple charts in one configmap
  .patches/getter.patch.go
  vendor/helm.sh/helm/v3/pkg/getter/getter.patch.go
Labels: approved, lgtm, ok-to-test
