Repository openshift-psap/special-resource-operator, pull requests merged in 2021-02, with the labels that each got.

#3 Add finalizers for specialresources add metrics.go framework and two basic metrics
  .github/workflows/image.yaml
  .github/workflows/lint.yaml
  .github/workflows/openshift.yaml
  .github/workflows/unit.yaml
  .github/workflows/verify.yaml
  Makefile
  config/manager/kustomization.yaml
  config/manifests/bases/special-resource-operator.clusterserviceversion.yaml
  config/prometheus/monitor.yaml
  config/samples/sro_v1beta1_specialresource.yaml
  controllers/finalizers.go
  controllers/resources.go
  controllers/specialresource.go
  controllers/status.go
  controllers/upgrade.go
  manifests/0012_deployment_special-resource-controller-manager.yaml
  manifests/0014_servicemonitor_special-resource-controller-manager-metrics-monitor.yaml
  pkg/conditions/conditions.go
  pkg/metrics/metrics.go
  test/deploy/deploy.go
  test/e2e/basic/available.go
  test/e2e/basic/simple-kmod.go
  test/e2e/basic/util.go
  test/undeploy/undeploy.go
Labels: approved, lgtm, tide/merge-method-squash

#15 Added new KernelPatchVersion
  .github/workflows/image-master.yaml
  .github/workflows/image.yaml
  .github/workflows/lint.yaml
  .github/workflows/openshift.yaml
  .github/workflows/unit.yaml
  .github/workflows/verify.yaml
  config/manager/kustomization.yaml
  config/manifests/bases/special-resource-operator.clusterserviceversion.yaml
  config/recipes/lustre-client/0000-lustre-client-cr.yaml
  config/recipes/lustre-client/manifests/0000-buildconfig.yaml
  config/recipes/lustre-client/manifests/1000-driver-container.yaml
  config/recipes/mlnx-rdma-shared/manifests/gpudirect/1000-state-driver.yaml
  config/recipes/mlnx-rdma-shared/manifests/mofed/0000-state-driver-buildconfig.yaml
  config/recipes/mlnx-rdma-shared/manifests/mofed/1000-state-driver.yaml
  config/recipes/nvidia-gpu/manifests/0000-state-driver-buildconfig.yaml
  config/recipes/nvidia-gpu/manifests/1000-state-driver.yaml
  config/recipes/nvidia-vran/manifests/gdrdrv/1000-state-driver.yaml
  config/recipes/nvidia-vran/manifests/gpudirect/1000-state-driver.yaml
  config/recipes/nvidia-vran/manifests/mofed/0000-state-driver-buildconfig.yaml
  config/recipes/nvidia-vran/manifests/mofed/1000-state-driver.yaml
  config/recipes/simple-kmod/0000-simple-kmod-cr.yaml
  config/recipes/simple-kmod/manifests/0000-buildconfig..yaml
  config/recipes/simple-kmod/manifests/1000-driver-container.yaml
  config/samples/sro_v1beta1_specialresource.yaml
  controllers/runtime.go
  manifests/0012_deployment_special-resource-controller-manager.yaml
Labels: approved, lgtm

#20 Removed uneeded pull_request target
  .github/workflows/image-build.yaml
  .github/workflows/image-master.yaml
  .github/workflows/image-remove.yaml
  .github/workflows/openshift.yaml
Labels: approved, lgtm, ok-to-test, tide/merge-method-squash

#22 Adding conditional checks for main and forked repositories
  .github/workflows/go-lint.yaml
  .github/workflows/image-build.yaml
  .github/workflows/image-master.yaml
  .github/workflows/image-remove.yaml
  .github/workflows/kube-lint.yaml
  .github/workflows/openshift.yaml
  .github/workflows/test.yaml
  .github/workflows/unit.yaml
  .github/workflows/verify.yaml
  test/e2e/basic/simple-kmod.go
Labels: approved, lgtm, tide/merge-method-squash

#23 Add workflow to kick off CI workflows when labeled ok-to-test
  .github/workflows/image-master.yaml
  .github/workflows/image-remove.yaml
  .github/workflows/run-tests.yaml
Labels: approved, lgtm, ok-to-test

#16 Add relatedObjects to ClusterOperator for must-gather
  controllers/status.go
  test/e2e/basic/available.go
Labels: approved, lgtm, ok-to-test
